application: fuzzyhipster
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: public/css
  
- url: /js
  static_dir: public/js
  
- url: /fonts
  static_dir: public/fonts

- url: /(.*\.(gif|png|jpg|ico))
  static_files: public/img/\1
  upload: images/(.*\.(gif|png|jpg|ico))
  
- url: /.*
  script: _go_app